# EXCELSIOR GENERATED STUB: Snowflake Connector
# Use this as stubs/snowflake/connector.pyi to satisfy W9019 and enable LoD checks.
from typing import Any, List, Optional

class SnowflakeConnection:
    def cursor(self) -> SnowflakeCursor: ...
    def close(self) -> None: ...

class SnowflakeCursor:
    def execute(self, command: str, params: Optional[Any] = None) -> SnowflakeCursor: ...
    def fetchall(self) -> List[tuple]: ...
    def fetchone(self) -> Optional[tuple]: ...
    @property
    def rowcount(self) -> int: ...

def connect(**kwargs: Any) -> SnowflakeConnection: ...
