# EXCELSIOR GENERATED STUB: Snowflake Connector
# Use this as stubs/snowflake/connector.pyi to satisfy W9019 and enable LoD checks.

from typing import Any

class SnowflakeConnection:
    def cursor(self) -> SnowflakeCursor: ...
    def close(self) -> None: ...


class SnowflakeCursor:
    def execute(self, command: str,
                params: Any | None = None) -> SnowflakeCursor: ...

    def fetchall(self) -> list[tuple]: ...
    def fetchone(self) -> tuple | None: ...
    @property
    def rowcount(self) -> int: ...


def connect(**kwargs: Any) -> SnowflakeConnection: ...
